### PR TITLE
remove slf4j v1 support

### PR DESCRIPTION
**Pull request by pjfanning**
* across the pekko modules for v1.1 releases, we are upgrading to slf4j v2
* this PR largely undoes https://github.com/apache/pekko-management/pull/137
* managementLoglevelsLog4j2Slf4j2 was added to Pekko Management after the 1.0.0 release to try to support slf4jv2 as well as slf4jv1
    * no subsequent Pekko Management release has happened
    * noone has complained
* Idea for Pekko Management 1.1.0 would be to only support slf4j v2 so managementLoglevelsLog4j2 will be changed to support just slf4j v2 and that means no need for managementLoglevelsLog4j2Slf4j2

### CODE REVIEW

**Comment by mdedetrich** [comment]
Is this technically a binary breaking change? Im asking not to block the PR, but rather if this is the case then we should make an agreement on versioning (i.e. we should bump pekko-management to 2.x.x)

**Comment by pjfanning** [comment]
> Is this technically a binary breaking change? Im asking not to block the PR, but rather if this is the case then we should make an agreement on versioning (i.e. we should bump pekko-management to 2.x.x)

I don't understand why updating slf4j to 2.x is a major change here but we've changed in every other module including pekko core modules. I want to call all the new releases 2.0.0 - but if we insist on calling the next pekko core release 1.1 - then it is completely inconsistent to say this is a breaking change. Note that the changes in https://github.com/apache/pekko-management/pull/137 have never been released and I would not be averse to reverting https://github.com/apache/pekko-management/pull/137 in the 1.0.x branch.

**Comment by mdedetrich** [comment]
> but if we insist on calling the next pekko core release 1.1 - then it is completely inconsistent to say this is a breaking change

There is no ambiguity to inconsistency when it comes to semantic version. If it breaks ABI/binary compatibility for public API then you increment the major, otherwise you increment the minor. Pekko 1.1.x has zero breaking changes to its public API so there is no debate there, its about the other modules (i.e. pekko-persistence-jdbc,  pekko-connectors) where we did break ABI for various reasons where it matters.

**Comment by pjfanning** [comment]
This PR is basically an undoing of https://github.com/apache/pekko-management/pull/137 and an upgrade of slf4j to v2.
All other Pekko main branches require slf4j v2 and logging implementations that work with slf4j v2. So to repeat, I cannot see how this change requires us to call the release v2 when no other module will be called v2.

**Review by mdedetrich — APPROVED** [review]
Thanks for explaining, lgtm but @raboof should check just incase I miss something

**Review by He-Pin — APPROVED** [review]
Thanks

**Pull request merged**
