### PR TITLE
update scala and logging jars

### PR DESCRIPTION
**Pull request by pjfanning**
minor bump in logging jars too

### CODE REVIEW

**Review by laglangyue — COMMENTED** [review]
lgtm

**Review by He-Pin — APPROVED** [review]
lgtm, but this pr is not just update scala version:)

**Comment by mdedetrich** [comment]
Agree with @He-Pin lets do our best to not do multiple things in same PR. Its nice to maintain a clean git log especially when we need to cherry pick (i.e. we typically backport Scala upgrades but not general dependency updates).

**Comment by pjfanning** [comment]
> Agree with @He-Pin lets do our best to not do multiple things in same PR. Its nice to maintain a clean git log especially when we need to cherry pick (i.e. we typically backport Scala upgrades but not general dependency updates).

there is no branch to backport to - main is the only branch

**Pull request merged**
