### PR TITLE
double timeout on flaky test

### PR DESCRIPTION
**Pull request by pjfanning**
see #216

### CODE REVIEW

**Review by raboof — APPROVED** [review]
I wonder if we already set `pekko.test.timefactor` (https://pekko.apache.org/docs/pekko/current/general/configuration-reference.html#pekko-testkit), but this is OK in any case.

**Comment by pjfanning** [comment]
The same flaky test failed even with the timefactor=2 - but the timefactor didn't seem to increase the timeout - it still looks like the same same short 1.5 second timeout.

```
[info] - should be able to be created *** FAILED *** (1 second, 459 milliseconds)
[info]   The future returned an exception of type: org.apache.pekko.coordination.lease.LeaseTimeoutException, with message: Timed out removing lease [lease-1]. It is not known if the remove happened. Is the API server up?. (KubernetesApiSpec.scala:104)
[info]   org.scalatest.exceptions.TestFailedException:
```

**Comment by raboof** [comment]
hmm, maybe because this test *explicitly* sets it to `testKitSettings.DefaultTimeout.duration`? What happens when we remove that? sorry for leading you down this rabbit hole :/

**Comment by pjfanning** [comment]
Without the explicit patience config, things get far worse. All the individual scenarios timeout in 150ms.

**Comment by pjfanning** [comment]
I'll merge the original change that just doubles the time on the patience config in this test class.

**Pull request merged**
